export const ConstantColorGuessMap = [
    [/success/, 'success'],
    [/complete/, 'success'],
    [/finish/, 'success'],
    [/enable/, 'success'],
    [/online/, 'success'],
    [/confirm/, 'success'],
    [/verified/, 'success'],
    [/idle/, 'warning'],
    [/configing/, 'warning'],
    [/create/, 'warning'],
    [/wait_/, 'warning'],
    [/error/, 'danger'],
    [/disabled/, 'danger'],
    [/fail/, 'danger'],
    [/offline/, 'danger'],
    [/refund/, 'danger'],
    [/reject/, 'danger'],
    [/not_/, 'warning'],
]
